name: ci

on: 
  workflow_dispatch:
    inputs:
      id:
        description: 'Run ID.'
        required: false
jobs:
  id:
    name: Workflow ID Provider
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.event.foo.inputs.id}}
        run: echo run identifier ${{ inputss.id }}
  validation:
    name: Validation
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        version: [10, 12]
    runs-on: ${{ matrix.os }}
    steps:
      - name: sleep
        run: sleep 2m
